import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import {Quicksand} from "next/font/google"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const quicksand = Quicksand({
  weight: "400", 
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "The Time Machine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} bg-cyan-950 text-gray-300`}
      >
        {children}
      </body> 
    </html>
  );
}
